# Generated by Django 4.2.14 on 2024-08-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_bookmark_category_comment_editorial_initcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemmeta',
            old_name='problem',
            new_name='problem_id',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='editorial_id',
        ),
        migrations.AddField(
            model_name='problem',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.editorial'),
        ),
        migrations.AlterField(
            model_name='initcode',
            name='run_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='initcode',
            name='template_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='problemmeta',
            name='ex_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemmeta',
            name='ex_out',
            field=models.TextField(blank=True, null=True),
        ),
    ]
