# Generated by Django 4.2.14 on 2024-08-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_rename_problem_problemmeta_problem_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='editorial',
            new_name='editorial_id',
        ),
    ]
