# Generated by Django 4.2.14 on 2024-08-08 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_rename_editorial_problem_editorial_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSolveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='rest_submis_last_at_416a45_idx',
        ),
        migrations.RemoveIndex(
            model_name='submissiondetail',
            name='rest_submis_submitt_9fdb3a_idx',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_type',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='last_attempt_at',
            new_name='submitted_at',
        ),
        migrations.RenameField(
            model_name='submissiondetail',
            old_name='cpu_time',
            new_name='testcase_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_solved',
        ),
        migrations.RemoveField(
            model_name='submissiondetail',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='submissiondetail',
            name='passed_num',
        ),
        migrations.RemoveField(
            model_name='submissiondetail',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='submissiondetail',
            name='submitted_code',
        ),
        migrations.RemoveField(
            model_name='submissiondetail',
            name='total_num',
        ),
        migrations.AddField(
            model_name='submission',
            name='final_result',
            field=models.TextField(default='WRONG'),
        ),
        migrations.AddField(
            model_name='submission',
            name='language_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.language'),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='editorial_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.editorial'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-submitted_at'], name='rest_submis_submitt_5641ca_idx'),
        ),
        migrations.AddField(
            model_name='usersolvestatus',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.problem'),
        ),
        migrations.AddField(
            model_name='usersolvestatus',
            name='submission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.submission'),
        ),
        migrations.AddField(
            model_name='usersolvestatus',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
