# Generated by Django 4.2.14 on 2024-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_usersolvestatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='original', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
