# Generated by Django 4.2.14 on 2024-08-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_remove_profile_user_name_user_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSolveStatus',
        ),
    ]
