# Generated by Django 4.2.14 on 2024-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_delete_usersolvestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
