# Generated by Django 4.2.14 on 2024-08-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_rename_user_name_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initcode',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_codes', to='rest.language'),
        ),
        migrations.AlterField(
            model_name='initcode',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_codes', to='rest.problem'),
        ),
        migrations.AlterField(
            model_name='problemmeta',
            name='problem_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='problem_meta', serialize=False, to='rest.problem'),
        ),
        migrations.AlterField(
            model_name='submissiondetail',
            name='submission_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='submission_detail', serialize=False, to='rest.submission'),
        ),
    ]
