# Generated by Django 4.2.14 on 2024-08-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_alter_initcode_language_id_alter_initcode_problem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemmeta',
            name='ex_in',
        ),
        migrations.RemoveField(
            model_name='problemmeta',
            name='ex_out',
        ),
        migrations.AddField(
            model_name='problemmeta',
            name='testcase',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemmeta',
            name='problem_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest.problem'),
        ),
    ]
