# Generated by Django 4.2.14 on 2024-08-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_remove_problemmeta_ex_in_remove_problemmeta_ex_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='avg_memory',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='avg_run_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
