# Generated by Django 4.2.14 on 2024-09-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_submission_avg_memory_submission_avg_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmeta',
            name='max_cpu_time',
            field=models.BigIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='problemmeta',
            name='max_memory',
            field=models.BigIntegerField(default=268435456),
        ),
        migrations.AddField(
            model_name='problemmeta',
            name='max_real_time',
            field=models.BigIntegerField(default=15000),
        ),
    ]
