# Generated by Django 4.2.14 on 2024-09-03 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_problemmeta_max_cpu_time_problemmeta_max_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemmeta',
            name='max_cpu_time',
        ),
        migrations.RemoveField(
            model_name='problemmeta',
            name='max_memory',
        ),
        migrations.RemoveField(
            model_name='problemmeta',
            name='max_real_time',
        ),
        migrations.CreateModel(
            name='CodeJudgeMaxConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cpu_time', models.BigIntegerField(default=5000)),
                ('max_real_time', models.BigIntegerField(default=15000)),
                ('max_memory', models.BigIntegerField(default=268435456)),
                ('language_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.language')),
                ('problem_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.problem')),
            ],
        ),
    ]
