# Generated by Django 4.2.14 on 2024-09-03 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_remove_problemmeta_max_cpu_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codejudgemaxconstraint',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.language'),
        ),
        migrations.AlterField(
            model_name='codejudgemaxconstraint',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.problem'),
        ),
    ]
