# Generated by Django 4.2.14 on 2024-09-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_alter_codejudgemaxconstraint_language_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user_id', 'problem_id')},
        ),
        migrations.AlterUniqueTogether(
            name='codejudgemaxconstraint',
            unique_together={('problem_id', 'language_id')},
        ),
        migrations.AlterUniqueTogether(
            name='initcode',
            unique_together={('problem_id', 'language_id')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user_id', 'problem_id')},
        ),
    ]
